### ISSUE TITLE
getting error can not not find -lcuda  while compiling AreTomo2 on Redhat8 

### ISSUE THREAD

**Issue by aplearnercc** [czimaginginstitute/AreTomo2#24]
Getting below error in spite of giving cuda library path in the make file.
/usr/bin/ld : can not not find -lcuda error while compiling the software.
Error screenshot has been attached. Please help!

![error1](https://github.com/user-attachments/assets/7c65d706-707e-4c2c-94f0-6f94c593ba80)
![error2](https://github.com/user-attachments/assets/d9dbde1f-7e3c-45d9-8b2c-dce2828ffd00)
![libloc](https://github.com/user-attachments/assets/55a052e0-63a8-42a8-97dc-ec23ece13c3e)

Regards,
Aparna

**Comment by alncat** [comment]
libcuda.so is normally located at $CUDA_HOME/targets/x86_64-linux/lib/stubs/. You may check my makefile in https://github.com/czimaginginstitute/AreTomo2/issues/23#issuecomment-2244069011, and change the $CUDA_HOME according to your system settings.

**Comment by aplearnercc** [comment]
I am still getting the same error. Pasting screenshot of makefile11. installer is still searching for libcuda.so in /usr/.. folder
![image](https://github.com/user-attachments/assets/b9014899-3931-4777-980d-3b55611c20b0)
![image](https://github.com/user-attachments/assets/a8dcde30-3c97-41ce-b9be-e10a9f1c4b64)

Regards,
Aparna

**Comment by alncat** [comment]
did you change the target:
```
exe: $(OBJS)
        @g++ -g -pthread -m64 $(OBJS) \
        $(PRJLIB)/libmrcfile.a \
        $(PRJLIB)/libutil.a \
        -L$(CUDALIB) -L/usr/lib64 -L$(CUDALLIB) \
        -lcufft -lcudart -lcuda -lc -lm -lpthread \
        -o AreTomo2
        @echo AreTomo2 has been generated.
```
in makefile11, I explicitly specify -L$(CUDALLIB) in the exe target.

**Comment by aplearnercc** [comment]
Thanks a lot! I had not noticed that. It successfully compiled now.

**Comment by alncat** [comment]
You are welcome!
