### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by kparey** [czimaginginstitute/AreTomo2#4]
We always get this error message and would be very grateful for help

![Screenshot from 2023-11-06 10-50-07](https://github.com/czimaginginstitute/AreTomo2/assets/150017906/ed628950-d517-4d8b-9380-38ea4d4eb1ee)

**Comment by wlugmayr** [comment]
I have a similar problem with libmrcfile.a. On CentOS7 & CentOS9 it does not appear, but on a Ubuntu workstation.

$ make
/usr/bin/ld: /home/lugmayr/aretomo2-1.0.0/Lib/libmrcfile.a(CLoadExtHeader.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:179: exe] Error 1

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by wlugmayr** [comment]
Doing it like AreTomo2 #4 solved the issue.

Link with 
exe: $(OBJS)
    @$(NVCC) -g -G -m64 $(OBJS) \
    $(PRJLIB)/libmrcfile.a $(PRJLIB)/libutil.a $(PRJLIB)/libcuutil.a \
    -L$(CUDALIB) \
    -L$(CONDA)/lib \
    -L/usr/lib64 \
    -Xcompiler -no-pie \
    -lcufft -lcudart -lcuda -lnvToolsExt -ltiff -lc -lm -lpthread \
    -o MotionCor3
    @echo MotionCor3 has been generated.

**Comment by kparey** [comment]
Dear all, I'm sorry to come back with the problem. We tried to compile AreTomo on CentOS 7.9. But unfortunately it doesn't work either. In addition, we don't know exactly what is meant in the last comment. We would definitely be happy if we could get this working and thank you in advance. Best regards, Kristian

**Comment by wlugmayr** [comment]
Oh sorry, the example should have gone to the motioncor3 github issue (similar to this one).

Edit the Makefile and set CUDAHOME to your needs e.g. /usr/local/cuda-11.8

and change the exe: target in the Makefile to
exe: $(OBJS)
	@$(NVCC) -g -G -m64 $(OBJS) \
	$(PRJLIB)/libmrcfile.a \
	$(PRJLIB)/libutil.a \
	$(CUPRJLIB)/libcuutil.a \
	$(CUPRJLIB)/libcuutilfft.a \
	-L$(CUDALIB) -L/usr/lib64 \
	-Xcompiler -no-pie \
	-lcufft -lcudart -lcuda -lc -lm -lpthread \
	-o AreTomo2
	@echo AreTomo2 has been generated.
