### ISSUE TITLE
compiling error 

### ISSUE THREAD

**Issue by jychoi0616** [czimaginginstitute/AreTomo2#5]
Hi,

I've got this error message below while compiling:

/data/AreTomo2/Lib/libmrcfile.a(CLoadMrc.o): In function `Mrc::CLoadMrc::CLoadMrc()':
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:14: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:15: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:16: undefined reference to `operator delete(void*, unsigned long)'
/data/AreTomo2/Lib/libmrcfile.a(CLoadMrc.o): In function `Mrc::CLoadMrc::~CLoadMrc()':
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:24: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:25: undefined reference to `operator delete(void*, unsigned long)'
/data/AreTomo2/Lib/libmrcfile.a(CLoadMrc.o):/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:26: more undefined references to `operator delete(void*, unsigned long)' follow
/data/AreTomo2/Lib/libutil.a(Util_LinEqs.o): In function `Util_LinEqs::DoIt(float*, float*, int)':
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:26: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:27: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:28: undefined reference to `__cxa_throw_bad_array_new_length'
/data/AreTomo2/Lib/libutil.a(Util_LinEqs.o): In function `Util_LinEqs::mSwapRows(float*, float*, int)':
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:97: undefined reference to `__cxa_throw_bad_array_new_length'
/data/AreTomo2/Lib/libutil.a(Util_Powell.o): In function `Util_Powell::~Util_Powell()':
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:22: undefined reference to `operator delete(void*, unsigned long)'
/data/AreTomo2/Lib/libutil.a(Util_Powell.o): In function `Util_Powell::Setup(int, int, float)':
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:48: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:49: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:50: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:51: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_Powell.cpp:52: undefined reference to `__cxa_throw_bad_array_new_length'
/data/AreTomo2/Lib/libutil.a(Util_Powell.o):/home/shawn.zheng/Projs/Util/Util_Powell.cpp:82: more undefined references to `__cxa_throw_bad_array_new_length' follow
/data/AreTomo2/Lib/libutil.a(Util_Thread.o): In function `Util_Thread::~Util_Thread()':
/home/shawn.zheng/Projs/Util/Util_Thread.cpp:18: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make: *** [exe] Error 1

Could you help me please?

Thanks a lot,

**Comment by szhengczii** [comment]
@jychoi0616, can you please run "g++ --version" and let me know what is printed out. Below is what I have.
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jychoi0616** [comment]
Hi!
mine is 4.8.5
Below is the printout:
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by AssmannG** [comment]
Loading the correct GCC/8.5.0 also fixed the issue for me.
