### ISSUE TITLE
Question: does AreTomo2 implement CTF correction?

### ISSUE THREAD

**Issue by McHaillet** [czimaginginstitute/AreTomo2#9]
Dear developers,

Thanks for all the nice work on this project and for open sourcing it, really appreciated!

I was wondering whether AreTomo2 implements CTF correction during reconstruction. From your code base it seems there is some CTF correction (CTFCor/CCorrTomoStack.cpp), but when I tried the software it did not become clear to me how this is applied. Do you have any documentation on this? Secondly, if it is applied what sort of scheme are you using for the correction?

Best wishes,
Marten

**Comment by apeck12** [comment]
Hi Marten,
AreTomo2 performs a per-tilt CTF estimation but does not correct for it during reconstruction in case a local CTF correction is applied during subsequent subtomogram averaging. It’s great to hear from the community, so please reach out with any further questions.
Best,
Ariana
